services:
  postgres:
    image: postgres:17

    container_name: boardgame-postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminstas
      POSTGRES_DB: boardgame_booking

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: